name: lint and test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Lint with pylint
      run: |
        find . -type f -name "*.py" | xargs pipenv run pylint --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        export PYTHONPATH=.
        pipenv run python -m pytest -s

    - name: Build docker image
      run: docker build -t biolib/openprotein .

    - name: Push docker image to Docker Hub if on master branch
      run: >-
        if [ ${GITHUB_REF#refs/heads/} = 'master' ]; then
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin &&
        docker push biolib/openprotein:latest ;
        fi
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
